name: NanUI CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    runs-on: windows-latest
    steps:
      - name: Setup MSBuild
        id: setup_msbuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build solution
        continue-on-error: true
        id: build_solution
        shell: powershell
        run: |
          msbuild .\NetDimension.NanUI.sln

# Built with ❤ by [Pipeline Foundation](https://pipeline.foundation)